# a tester
---
- name: Manage cron and at configurations
  become: true # Utilisation de privilèges élevés pour les tâches
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/at.deny
    - /etc/cron.deny
  tags:
      - at
      - cron

# Utilisation de privilèges élevés pour les tâches
- name: Clean cron and at allow files
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    regexp: "^(?!root).*$"
    state: absent
  with_items:
    - /etc/at.allow
    - /etc/cron.allow
  tags:
    - at
    - cron
    - CIS-UBUNTU2004-5.1.8
    - CIS-UBUNTU2004-5.1.9

# Cette tâche ajoute la ligne "root" dans les fichiers /etc/at.allow et /etc/cron.allow, en créant les fichiers s'ils n'existent pas
- name: Allow root user for cron and at
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    line: "root"
    mode: '0600'
    state: present
    create: true
  with_items:
    - /etc/at.allow
    - /etc/cron.allow
  tags:
    - at
    - cron
# Masque, désactive et arrête le service atd pour empêcher son démarrage
- name: Mask atd service
  ansible.builtin.systemd:
    name: atd
    masked: true
    enabled: false
    state: stopped
  register: mask_atd
  failed_when: mask_atd is not success and not "Could not find the requested service" in mask_atd.msg
  tags:
    - at
    - systemd

# Configure les permissions sur les répertoires associés à cron pour garantir que seul root a accès
- name: Set permissions for cron directories
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0700'
    owner: root
    group: root
  with_items:
    - /etc/cron.d
    - /etc/cron.daily
    - /etc/cron.hourly
    - /etc/cron.weekly
    - /etc/cron.monthly
  tags:
    - cron
    - CIS-UBUNTU2004-5.1.3
    - CIS-UBUNTU2004-5.1.4
    - CIS-UBUNTU2004-5.1.5
    - CIS-UBUNTU2004-5.1.6
    - CIS-UBUNTU2004-5.1.7

# Configure les permissions du fichier /etc/crontab pour garantir que seul root a accès
- name: Set permissions for crontab file
  ansible.builtin.file:
    path: /etc/crontab
    mode: '0600'
    owner: root
    group: root
  tags:
    - cron
    - crontab
    - CIS-UBUNTU2004-5.1.2
