---
- name: Stat faillock
  become: true
  ansible.builtin.find:
    paths: ['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin', '/snap/bin']
    patterns: "faillock"
    recurse: true
  register: faillock
  tags:
    - common-account
    - common-auth
    - pam

- name: Stat faillock configuration file
  become: true
  ansible.builtin.stat:
    path: /etc/security/faillock.conf
  register: faillockconf
  tags:
    - common-account
    - common-auth
    - pam

- name: Configure faillock.conf
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/security/faillock.conf
    mode: 0644
    state: present
    line: "{{ item }}"
  with_items:
    - "audit"
    - "local_users_only"
    - "deny = 5"
    - "fail_interval = 900"
  when: faillockconf.stat.exists
  tags:
    - common-account
    - common-auth
    - pam

- name: Debian OS family PAM configuration
  become: true
  when: ansible_os_family == "Debian"
  block:
    - name: Configure common-password
      ansible.builtin.template:
        src: etc/pam.d/common-password.j2
        dest: /etc/pam.d/common-password
        backup: true
        mode: 0644
        owner: root
        group: root
      tags:
        - common-password
        - pam
        - CIS-UBUNTU2004-5.4.3
        - CIS-UBUNTU2004-5.4.4
        - UBTU-20-010070

    - name: Configure common-auth
      ansible.builtin.template:
        src: etc/pam.d/common-auth.j2
        dest: /etc/pam.d/common-auth
        backup: true
        mode: 0644
        owner: root
        group: root
      tags:
        - common-auth
        - pam
        - CIS-UBUNTU2004-5.4.2
        - M1036
        - UBTU-20-010072

    - name: Configure common-account
      ansible.builtin.template:
        src: etc/pam.d/common-account.j2
        dest: /etc/pam.d/common-account
        backup: true
        mode: 0644
        owner: root
        group: root
      tags:
        - common-account
        - pam
        - M1036

    - name: Configure login
      ansible.builtin.template:
        src: etc/pam.d/login.j2
        dest: /etc/pam.d/login
        backup: true
        mode: 0644
        owner: root
        group: root
      tags:
        - login
        - pam
        - UBTU-20-010075

    - name: Configure sshd
      ansible.builtin.template:
        src: etc/pam.d/sshd.j2
        dest: /etc/pam.d/sshd
        backup: true
        mode: 0644
        owner: root
        group: root
      tags:
        - sshd
        - pam
        - UBTU-20-010075

    - name: Configure cloud
      ansible.builtin.template:
        src: etc/cloud/cloud.j2
        dest: /etc/cloud/cloud.cfg
        backup: true
        mode: 0644
        owner: root
        group: root
      tags:
        - cloud
        - cloud-init
        - UBTU-20-010075

- name: RedHat OS family PAM configuration
  become: true
  when: ansible_os_family == "RedHat"
  block:
    - name: Remove nullok from system-auth
      ansible.builtin.replace:
        dest: /etc/pam.d/system-auth
        regexp: 'nullok'
        mode: 0644
        owner: root
        group: root
      tags:
        - system-auth
        - pam
        - CCE-80841-0

    - name: Remove nullok from password-auth
      ansible.builtin.replace:
        dest: /etc/pam.d/password-auth
        regexp: 'nullok'
        mode: 0644
        owner: root
        group: root
      tags:
        - password-auth
        - pam

    - name: Remove nullok from sssd-shadowutils
      become: true
      ansible.builtin.replace:
        dest: /etc/pam.d/sssd-shadowutils
        regexp: 'nullok'
        mode: 0644
        owner: root
        group: root
      tags:
        - sssd-shadowutils
        - pam

    - name: Set system-auth remember
      ansible.builtin.replace:
        regexp: 'use_authtok(\s+.*)'
        replace: "use_authtok remember=5"
        dest: /etc/pam.d/system-auth
        mode: 0644
        owner: root
        group: root
      tags:
        - system-auth
        - CCE-80666-1

- name: Stat libuser configuration
  become: true
  ansible.builtin.stat:
    path: /etc/libuser.conf
  register: libuser
  tags:
    - libuser

- name: Set libuser crypt_style to sha512
  become: true
  ansible.builtin.replace:
    regexp: 'crypt_style(\s+.*)'
    replace: "crypt_style = sha512"
    dest: /etc/libuser.conf
    mode: 0644
    owner: root
    group: root
  when: libuser.stat.exists
  tags:
    - libuser
    - CCE-80891-5
